# syntax=docker/dockerfile:1

ARG PYTHON_VERSION=3.14
ARG BASE=trixie
ARG UV_VERSION=0.9.7

FROM ghcr.io/astral-sh/uv:${UV_VERSION}-python${PYTHON_VERSION}-${BASE}-slim AS uv

FROM python:${PYTHON_VERSION}-slim-${BASE}

ENV PYTHONDONTWRITEBYTECODE=1 \
    PYTHONUNBUFFERED=1 \
    UV_LINK_MODE=copy
WORKDIR /app

COPY --from=uv /usr/local/bin/uv /usr/local/bin/uvx /bin/

RUN --mount=type=cache,id=uv-cache,target=/root/.cache/uv \
    --mount=type=bind,source=uv.lock,target=uv.lock \
    --mount=type=bind,source=pyproject.toml,target=pyproject.toml \
    uv sync --frozen --no-install-workspace

COPY . .

RUN --mount=type=cache,id=uv-cache,target=/root/.cache/uv \
    uv sync --locked

ENV PATH="/app/.venv/bin:$PATH"

EXPOSE 80
CMD ["uv", "run", "uvicorn", "kiosk_manager.asgi:application", "--host", "0.0.0.0", "--port", "80", "--reload"]
