# Generated by Django 6.0.8 on 2026-08-16 00:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("kiosks", "0008_event"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="screencommand",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="kiosk_screen_commands",
                to=settings.AUTH_USER_MODEL,
                verbose_name="created by",
            ),
        ),
        migrations.AddConstraint(
            model_name="screencommand",
            constraint=models.UniqueConstraint(
                condition=models.Q(("acknowledged_at__isnull", True)),
                fields=("screen", "command"),
                name="kiosks_pending_command_unique",
            ),
        ),
    ]
