# Generated by Django 6.0.8 on 2026-08-16 01:06

from django.db import migrations, models


def populate_content_labels(apps, schema_editor):
    content_model = apps.get_model("kiosks", "Content")
    for content in content_model.objects.filter(label="").iterator():
        source = content.url or content.html_file or f"Content {content.pk}"
        content.label = str(source)[:200]
        content.save(update_fields=["label"])


class Migration(migrations.Migration):
    dependencies = [
        ("kiosks", "0009_screencommand_created_by_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="content",
            name="label",
            field=models.CharField(
                default="", max_length=200, verbose_name="label"
            ),
        ),
        migrations.RunPython(
            populate_content_labels, reverse_code=migrations.RunPython.noop
        ),
    ]
