# Generated by Django 6.0.8 on 2026-08-16 20:56

from django.db import migrations

import recurrence.fields


class Migration(migrations.Migration):
    dependencies = [
        ("kiosks", "0011_content_media"),
    ]

    operations = [
        migrations.AlterField(
            model_name="screen",
            name="off_schedule",
            field=recurrence.fields.RecurrenceField(
                blank=True,
                default="",
                help_text="Optional recurring times when screen should receive HDMI-CEC standby command. Times use the configured timezone.",
                verbose_name="power-off schedule",
            ),
        ),
        migrations.AlterField(
            model_name="screen",
            name="on_schedule",
            field=recurrence.fields.RecurrenceField(
                blank=True,
                default="",
                help_text="Optional recurring times when screen should receive HDMI-CEC on command. Times use the configured timezone.",
                verbose_name="power-on schedule",
            ),
        ),
    ]
