# Generated by Django 6.0.8 on 2026-08-16 21:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("kiosks", "0012_alter_screen_off_schedule_alter_screen_on_schedule"),
    ]

    operations = [
        migrations.AlterField(
            model_name="screencommand",
            name="command",
            field=models.CharField(
                choices=[
                    ("restart_agent", "restart agent"),
                    ("upgrade_agent", "upgrade agent"),
                ],
                max_length=32,
                verbose_name="command",
            ),
        ),
    ]
